test-syndic:
  tags:
    - salt-syndic
  stage: test
  script:
    - echo "Rendering pillar on syndics"
    - cd /srv/salt
    - git reset --hard
    - git clean -d -f
    - git pull
    - sudo salt '*' pillar.items

test-highstate:
  tags:
    - salt-master
  stage: test
  script:
    - echo "Testing highstate on master"
    - cd /srv/salt
    - git reset --hard
    - git clean -d -f
    - git pull
    - sudo salt '*' state.highstate test=true --state-output=changes

deploy-highstate:
  tags:
    - salt-master
  stage: deploy
  script:
    - echo "Deploying highstate from master"
    - sudo salt '*' state.highstate --state-output=changes

